services:
  - type: web
    name: blowfish-algo
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn blowfish_web:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
